# Change these first
owner: Reishandy # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Reishandy - reishandy.my.id
    url: https://reishandy.my.id
  - name: Bazaar - bazaar.reishandy.my.id
    url: https://bazaar.reishandy.my.id
  - name: Pixel Positions - pixel-positions.reishandy.my.id
    url: https://pixel-positions.reishandy.my.id
  - name: Kanban - kanban.reishandy.my.id
    url: https://kanban.reishandy.my.id
  - name: Guest Book API - guest-book.reishandy.my.id
    url: https://guest-book.reishandy.my.id
  - name: Comment Section API - comment-section.reishandy.my.id
    url: https://comment-section.reishandy.my.id
  - name: Chatroom API - chatroom.reishandy.my.id
    url: https://chatroom.reishandy.my.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  cname: status.reishandy.my.id
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Reishandy's Status
  introTitle: "**Reishandy's Services** Status Dashboard"
  introMessage: "Monitor the operational status of all Reishandy's services in real-time. This status page is powered by [Upptime](https://github.com/upptime/upptime), an open-source uptime monitor running on GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration